# Generated by Django 5.2 — Slice 5 / DEFER-0030 entity story FKs.
# Module 0010 avoids collision with PR #60 content.0009_scheduled_for_and_contentrevision.
# Depends on content.0008_article_story (same parent as PR #60's 0009 until one PR rebases).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("composition", "0002_compositionpage_kind"),
        ("content", "0008_article_story"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileexperience",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_profile_experiences",
                to="composition.compositionpage",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_projects",
                to="composition.compositionpage",
            ),
        ),
        migrations.AddField(
            model_name="researchstatement",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_research_statements",
                to="composition.compositionpage",
            ),
        ),
        migrations.AddField(
            model_name="researchtopic",
            name="story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attached_research_topics",
                to="composition.compositionpage",
            ),
        ),
    ]
